"""Add registered_by to student table only

Revision ID: 23c83e9e2d3b
Revises: 720b836fac44
Create Date: 2025-07-20 20:27:47.228734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23c83e9e2d3b'
down_revision = '720b836fac44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('registered_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student', 'user', ['registered_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column('student', 'registered_by')
    # ### end Alembic commands ###
