"""add logo field to school model

Revision ID: 6aeb8cdcaf79
Revises: a56e13d3eced
Create Date: 2025-11-09 21:00:42.084348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6aeb8cdcaf79'
down_revision = 'a56e13d3eced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_plan_feedback')
    op.drop_table('meal_plan_assignment')
    op.drop_table('notification')
    op.drop_table('meal_plan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_plan',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('school_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('section_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grade_level_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('breakfast', mysql.TEXT(), nullable=True),
    sa.Column('lunch', mysql.TEXT(), nullable=True),
    sa.Column('snack', mysql.TEXT(), nullable=True),
    sa.Column('total_calories', mysql.FLOAT(), nullable=True),
    sa.Column('protein', mysql.FLOAT(), nullable=True),
    sa.Column('carbohydrates', mysql.FLOAT(), nullable=True),
    sa.Column('fats', mysql.FLOAT(), nullable=True),
    sa.Column('fiber', mysql.FLOAT(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name='meal_plan_ibfk_4'),
    sa.ForeignKeyConstraint(['grade_level_id'], ['grade_level.id'], name='meal_plan_ibfk_3'),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], name='meal_plan_ibfk_1'),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], name='meal_plan_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('notification',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recipient_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], name='notification_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('meal_plan_assignment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meal_plan_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_date', mysql.DATETIME(), nullable=True),
    sa.Column('assigned_by', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], name='meal_plan_assignment_ibfk_3'),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plan.id'], name='meal_plan_assignment_ibfk_1'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='meal_plan_assignment_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('meal_plan_feedback',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meal_plan_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comments', mysql.TEXT(), nullable=True),
    sa.Column('meal_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('feedback_date', sa.DATE(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plan.id'], name='meal_plan_feedback_ibfk_1'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='meal_plan_feedback_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='meal_plan_feedback_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
