"""add logo to school

Revision ID: 7d3b4c8e2f9a
Revises: 6aeb8cdcaf79
Create Date: 2025-11-09 21:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d3b4c8e2f9a'
down_revision = '6aeb8cdcaf79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('logo', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school', 'logo')
    # ### end Alembic commands ###