"""Add report_id to notification

Revision ID: 83311b7676c6
Revises: 23c83e9e2d3b
Create Date: 2025-07-22 09:51:20.824235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83311b7676c6'
down_revision = '23c83e9e2d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'grade_level', ['grade_level_id'], ['id'])
        batch_op.drop_column('grade_level')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_level', mysql.VARCHAR(length=32), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('report_id')

    # ### end Alembic commands ###
