"""Add user activity history

Revision ID: a58db80f5f5e
Revises: c2f2c75ce475
Create Date: 2025-05-09 20:34:01.747419

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a58db80f5f5e'
down_revision = 'c2f2c75ce475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed problematic DROP TABLE statements
    # op.drop_table('allergies')
    # op.drop_table('sections')
    # with op.batch_alter_table('students', schema=None) as batch_op:
    #     batch_op.drop_index('user_id')
    # op.drop_table('students')
    # with op.batch_alter_table('users', schema=None) as batch_op:
    #     batch_op.drop_index('email')
    # op.drop_table('users')
    # op.drop_table('schools')
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('schools',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('school_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('login_attempts', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_login_attempt', mysql.DATETIME(), nullable=True),
    sa.Column('is_locked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('lock_until', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='users_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('students',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('section_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('height', mysql.FLOAT(), nullable=True),
    sa.Column('weight', mysql.FLOAT(), nullable=True),
    sa.Column('bmi', mysql.FLOAT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('school_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('preferences', mysql.VARCHAR(length=256), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='students_ibfk_3', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name='students_ibfk_2', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='students_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index('user_id', ['user_id'], unique=True)

    op.create_table('sections',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('grade_level', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('school_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='sections_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('allergies',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('allergen', mysql.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='allergies_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
