"""Add preferences column to Student model

Revision ID: c2f2c75ce475
Revises: 3481585a1bde
Create Date: 2025-05-06 21:45:07.281389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f2c75ce475'
down_revision = '3481585a1bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferences', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('preferences')

    # ### end Alembic commands ###
